### ISSUE TITLE
File Upload Configuration

### ISSUE THREAD

**Issue by billycheuk** [luxio/webform_multiple_file#2]
Hi luxio

I had all required and corresponding modules and installed and configured along the line and tried to upload files but in vain.  I added a upload media field in a Content Type and set the Field Type as Multimedia Asset and the Widget as Media Browser, and also managed the Drupalgap Display Format as Media.

On Drupalgap it rendered null with the following Console Warnings:

WARNING: _drupalgap_form_render_element() - media_field_widget_form() does not exist for the "media" form element!
WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.

Kindly enlighten and instruct further.

**Comment by luxio** [comment]
Hi billycheuk,

as mentioned in the readme this  is a submodule for the [DrupalGap Webform Module](https://github.com/signalpoint/webform) for uploading files in **webforms** which are using the Drupal [Webform Multiple File](https://www.drupal.org/project/webform_multiple_file) Module.

It does not work for content type fields, although you can use the code as base for a custom field widget for uploading multiple media files.

**Comment by billycheuk** [comment]
Hi luxio

It's so nice of you replying so soon.  I went back to create a webform and recorded console logs as follows:
WARNING: theme_liveloop_button() does not exist.
WARNING: theme_liveloop_button() does not exist.
WARNING: theme_liveloop_button() does not exist.
WARNING: theme_liveloop_button() does not exist.
WARNING: theme_liveloop_button() does not exist.
WARNING: theme_undefined() does not exist. Called by: drupalgap_render_page().

Seems a theme requirement I didn't notice.  I use my_theme in place of easystreet3.

Thank you in advance for your kind advice.

**Comment by luxio** [comment]
@billycheuk indeed, I have made some custom theme changes, please try the branch pick_multiple_images (https://github.com/luxio/webform_multiple_file/tree/pick_multiple_images) instead of the default branch.

**Comment by billycheuk** [comment]
@luxio

Now it works out like this with one warning:

WARNING: theme_undefined() does not exist. Called by: drupalgap_render_page().

Please don't mind to advise I should work it out on my own.

![webform_multiple_file_test1](https://cloud.githubusercontent.com/assets/13603698/20600890/d100191c-b290-11e6-80e6-cf39219ea3f6.png)

**Comment by luxio** [comment]
what happens if you press one of the buttons?

**Comment by billycheuk** [comment]
@luxio 

I tested it on an Android phone.

While nothing happens with the first and second buttons, the third turns out the audio recorder which works fine, the fourth turns out the video recorder which works fine and the fifth goes to the video folder which also works fine.

**Comment by billycheuk** [comment]
@luxio 

I tested again with the default branch, by replacing the theme_liveloop_button with button.

All work fine except the second button which should go to the picture folder (i.e. onclick not working).  That means the fifth button still can open the video folder.  Tracing the codes, yet I got no luck.

**Comment by luxio** [comment]
@billycheuk 

Have you installed the the [cordova-plugin-imagepicker](https://www.npmjs.com/package/cordova-plugin-imagepicker) plugin? I'm using this plugin in order to have the user select multiple images at once.

**Comment by billycheuk** [comment]
@luxio 

Really so kind of you to remind me of a missing plugin.  Now all are fine.  What an awesome and perfect workpiece of yours!

Thank you.

**Comment by luxio** [comment]
@billycheuk Thanks for the feedback.
